# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
description: ...

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@1.6.0


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: pytest
          name: run pytest

      - run:
          command: flake8
          name: run flake8



# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  master:
    jobs:
      - build-and-test

#      - docker/publish:
#          requires:
#            - build-and-test
#          image: cimg/base:stable
#            auth:
#              username: ludotreb
#              password: $DOCKERHUB_PASSWORD # context / project UI env-var reference ⚠️ chercher comment configurer ce fichier
#          filters:
#            branches:
#              only: project_13v02

      # configurer le deploiement
