version: 2.1
orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6
jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements-dev.txt
          pkg-manager: pipenv
#      - run:
#          name: run pytest
#          command: pipenv run pytest # alternatively run `python -m pytest` if you are running vanilla pytest
#      - run:
#          command: flake8
#          name: run flake8
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  heroku_deploy:
    jobs:
      - build_and_test
      - heroku/deploy-via-git:
          requires:
            - build_and_test
          filters:
            branches:
              only: master